/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BecomeCreatorRouteImport } from './routes/become-creator'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDashboardUploadRouteImport } from './routes/_app.dashboard.upload'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app.dashboard.settings'
import { Route as AppDashboardPurchasesRouteImport } from './routes/_app.dashboard.purchases'
import { Route as AppDashboardProductsRouteImport } from './routes/_app.dashboard.products'
import { Route as AppDashboardMyProductsRouteImport } from './routes/_app.dashboard.my-products'
import { Route as AppDashboardFavoritesRouteImport } from './routes/_app.dashboard.favorites'
import { Route as AppDashboardEarningsRouteImport } from './routes/_app.dashboard.earnings'
import { Route as AppDashboardAnalyticsRouteImport } from './routes/_app.dashboard.analytics'
import { Route as AppDashboardEditIdRouteImport } from './routes/_app.dashboard.edit.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeCreatorRoute = BecomeCreatorRouteImport.update({
  id: '/become-creator',
  path: '/become-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardUploadRoute = AppDashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardPurchasesRoute = AppDashboardPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardProductsRoute = AppDashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardMyProductsRoute = AppDashboardMyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardFavoritesRoute = AppDashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardEarningsRoute = AppDashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAnalyticsRoute = AppDashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardEditIdRoute = AppDashboardEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-creator': typeof BecomeCreatorRoute
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/dashboard/analytics': typeof AppDashboardAnalyticsRoute
  '/dashboard/earnings': typeof AppDashboardEarningsRoute
  '/dashboard/favorites': typeof AppDashboardFavoritesRoute
  '/dashboard/my-products': typeof AppDashboardMyProductsRoute
  '/dashboard/products': typeof AppDashboardProductsRoute
  '/dashboard/purchases': typeof AppDashboardPurchasesRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/upload': typeof AppDashboardUploadRoute
  '/dashboard/edit/$id': typeof AppDashboardEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-creator': typeof BecomeCreatorRoute
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/dashboard/analytics': typeof AppDashboardAnalyticsRoute
  '/dashboard/earnings': typeof AppDashboardEarningsRoute
  '/dashboard/favorites': typeof AppDashboardFavoritesRoute
  '/dashboard/my-products': typeof AppDashboardMyProductsRoute
  '/dashboard/products': typeof AppDashboardProductsRoute
  '/dashboard/purchases': typeof AppDashboardPurchasesRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/upload': typeof AppDashboardUploadRoute
  '/dashboard/edit/$id': typeof AppDashboardEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/become-creator': typeof BecomeCreatorRoute
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/_app/dashboard/analytics': typeof AppDashboardAnalyticsRoute
  '/_app/dashboard/earnings': typeof AppDashboardEarningsRoute
  '/_app/dashboard/favorites': typeof AppDashboardFavoritesRoute
  '/_app/dashboard/my-products': typeof AppDashboardMyProductsRoute
  '/_app/dashboard/products': typeof AppDashboardProductsRoute
  '/_app/dashboard/purchases': typeof AppDashboardPurchasesRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard/upload': typeof AppDashboardUploadRoute
  '/_app/dashboard/edit/$id': typeof AppDashboardEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-creator'
    | '/categories'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/register'
    | '/dashboard'
    | '/product/$id'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/favorites'
    | '/dashboard/my-products'
    | '/dashboard/products'
    | '/dashboard/purchases'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-creator'
    | '/categories'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/register'
    | '/dashboard'
    | '/product/$id'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/favorites'
    | '/dashboard/my-products'
    | '/dashboard/products'
    | '/dashboard/purchases'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/become-creator'
    | '/categories'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/register'
    | '/_app/dashboard'
    | '/product/$id'
    | '/_app/dashboard/analytics'
    | '/_app/dashboard/earnings'
    | '/_app/dashboard/favorites'
    | '/_app/dashboard/my-products'
    | '/_app/dashboard/products'
    | '/_app/dashboard/purchases'
    | '/_app/dashboard/settings'
    | '/_app/dashboard/upload'
    | '/_app/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BecomeCreatorRoute: typeof BecomeCreatorRoute
  CategoriesRoute: typeof CategoriesRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-creator': {
      id: '/become-creator'
      path: '/become-creator'
      fullPath: '/become-creator'
      preLoaderRoute: typeof BecomeCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/upload': {
      id: '/_app/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof AppDashboardUploadRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/purchases': {
      id: '/_app/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof AppDashboardPurchasesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/products': {
      id: '/_app/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AppDashboardProductsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/my-products': {
      id: '/_app/dashboard/my-products'
      path: '/my-products'
      fullPath: '/dashboard/my-products'
      preLoaderRoute: typeof AppDashboardMyProductsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/favorites': {
      id: '/_app/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AppDashboardFavoritesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/earnings': {
      id: '/_app/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof AppDashboardEarningsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/analytics': {
      id: '/_app/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AppDashboardAnalyticsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/edit/$id': {
      id: '/_app/dashboard/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof AppDashboardEditIdRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardAnalyticsRoute: typeof AppDashboardAnalyticsRoute
  AppDashboardEarningsRoute: typeof AppDashboardEarningsRoute
  AppDashboardFavoritesRoute: typeof AppDashboardFavoritesRoute
  AppDashboardMyProductsRoute: typeof AppDashboardMyProductsRoute
  AppDashboardProductsRoute: typeof AppDashboardProductsRoute
  AppDashboardPurchasesRoute: typeof AppDashboardPurchasesRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardUploadRoute: typeof AppDashboardUploadRoute
  AppDashboardEditIdRoute: typeof AppDashboardEditIdRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAnalyticsRoute: AppDashboardAnalyticsRoute,
  AppDashboardEarningsRoute: AppDashboardEarningsRoute,
  AppDashboardFavoritesRoute: AppDashboardFavoritesRoute,
  AppDashboardMyProductsRoute: AppDashboardMyProductsRoute,
  AppDashboardProductsRoute: AppDashboardProductsRoute,
  AppDashboardPurchasesRoute: AppDashboardPurchasesRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardUploadRoute: AppDashboardUploadRoute,
  AppDashboardEditIdRoute: AppDashboardEditIdRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BecomeCreatorRoute: BecomeCreatorRoute,
  CategoriesRoute: CategoriesRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
